#build.yaml
name: CI/CD Pipeline
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - AWS
jobs:
  tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '16'
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/online/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Run Tests
        working-directory: ./online
        run: mvn -B test
    docker:
        runs-on: ubuntu-latest
        name: A job to build and push docker
        steps:
          - name: Checkout code
            uses: actions/checkout@v2

          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v1

          - name: Login to Public ECR
            uses: docker/login-action@v1
            with:
              registry: public.ecr.aws
              username: ${{ secrets.AWS_ACCESS_KEY_ID }}
              password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            env:
              AWS_REGION: us-east-1

          - name: Build and push container
            uses: docker/build-push-action@v2
            with:
              context: .
              push: true
              tags: public.ecr.aws/d4e5g9s2/martin:latest